version: "3.3"

services:
  db:
    image: postgres
    #    volumes:
    #      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=RestAPIdb
      - POSTGRES_USER=RestAPIuser
      - POSTGRES_PASSWORD=Dk0p4XGxP4
  web:
    build: .
    command: bash -c "
      sleep 5 &&
      python shop/manage.py migrate &&
      python shop/manage.py runserver 0.0.0.0:8080"
    #    volumes:
    #      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always