version: '3'
services:

  mysqldb:
    image: mysql:latest
    #    ports:
    #      - "3306:3306"
    volumes:
      - "./db_data:/var/lib/mysql"
    #      - "mysql_config:/etc/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Dk0p4XGxP4root
      MYSQL_DATABASE: RestAPIdb
      MYSQL_USER: RestAPIuser
      MYSQL_PASSWORD: Dk0p4XGxP4
    restart: always

  shop:
    build: .
    ports:
      - "8080:8080"
    restart: always
    command: /bin/bash -c "pip install -r requirements.txt && python3 shop/manage.py migrate && python3 shop/manage.py runserver 0.0.0.0:8080"
    #    command: python3 shop/manage.py runserver 0.0.0.0:8080

    depends_on:
      - mysqldb
