# Generated by Django 3.1.7 on 2021-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор курьера')),
                ('courier_type', models.CharField(choices=[('foot', 10), ('bike', 15), ('car', 50)], max_length=255, verbose_name='Тип курьера')),
            ],
        ),
    ]
