# Generated by Django 3.1.7 on 2021-03-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='идентификатор курьера')),
                ('courier_type', models.CharField(choices=[('foot', 'Foot (10 kg)'), ('bike', 'Bike (15 kg)'), ('car', 'Car (50 kg)')], max_length=255, verbose_name='тип курьера')),
                ('regions', models.JSONField(verbose_name='районы работы')),
                ('working_hours', models.JSONField(verbose_name='рабочие часы')),
                ('assign_time', models.DateTimeField(null=True, verbose_name='Дата назначения заказов')),
                ('complete_time', models.DateTimeField(null=True, verbose_name='Дата завершения заказа')),
                ('time_regions', models.JSONField(null=True, verbose_name='Минимальное время доставки по району')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='идентификатор заказа')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='вес заказа')),
                ('region', models.PositiveIntegerField(verbose_name='район доставки')),
                ('delivery_hours', models.JSONField(verbose_name='часы доставки')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершён ли заказ')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.courier', verbose_name='взят курьером')),
            ],
        ),
    ]
