# Generated by Django 3.1.7 on 2021-03-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210318_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='total_earning',
            new_name='earning',
        ),
    ]
